---
- import_playbook: ../init/main.yml
  vars:
    l_init_fact_hosts: "oo_nodes_to_config"
    l_openshift_version_determine_hosts: "all:!all"
    l_openshift_version_set_hosts: "all:!all"
    skip_sanity_checks: True

- import_playbook: private/imageconfig.yml

- import_playbook: private/configure_system_container.yml
  when:
  - openshift_is_atomic | default(false) | bool
  - oreg_auth_user is defined or openshift_additional_registry_credentials != []
