apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /var/nfs-data/pv01
    server: 172.17.60.140
  persistentVolumeReclaimPolicy: Recycle
