apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
subsets:
  - addresses:
      - ip: 172.17.60.140
    ports:
      - port: 1
  - addresses:
      - ip: 172.17.60.142
    ports:
      - port: 1
  - addresses:
      - ip: 172.17.60.143
    ports:
      - port: 1
