---
# l_scale_up_hosts may be passed in via prerequisites.yml during scaleup plays.
# l_etcd_scale_up_crt_hosts may be passed in via prerequisites.yml during etcd
# scaleup plays.

- name: Configure container runtime
  hosts: "{{ l_etcd_scale_up_crt_hosts | default(l_scale_up_hosts) | default('oo_nodes_to_config') }}"

  tasks:
    - import_role:
        name: openshift_excluder
        tasks_from: enable.yml
      vars:
        r_openshift_excluder_action: enable
        r_openshift_excluder_enable_openshift_excluder: false

    - import_role:
        name: container_runtime
        tasks_from: install.yml
